name: swiggy
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.6
  carousel_slider: ^4.2.1
  material_floating_search_bar_2: ^0.5.0
  dropdown_button2: ^2.3.9
  animated_text_kit: ^4.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^3.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - assets/img/hotel/bhagwati.jpeg
    - assets/img/hotel/blue.jpg
    - assets/img/hotel/ch.jpg
    - assets/img/hotel/dil se.webp
    - assets/img/hotel/marriott.jpg
    - assets/img/hotel/marrito.jpg
    - assets/img/hotel/Mirchi.webp
    - assets/img/hotel/pizzaHut.jpg
    - assets/img/hotel/skyhotel.jpg

    - assets/img/plan/buffets.jpeg
    - assets/img/plan/budget.jpeg
    - assets/img/plan/family.jpeg
    - assets/img/plan/live-screening.jpg
    - assets/img/plan/outdoors.jpg
    - assets/img/plan/quick bites.jpg
    - assets/img/plan/veg.jpeg

    - assets/img/feature/indian.jpeg
    - assets/img/feature/italian.webp
    - assets/img/feature/jack.jpg
    - assets/img/feature/masala.jpg
    - assets/img/feature/pavilion.jpg
    - assets/img/feature/resturant.png
    - assets/img/feature/spice villa.jpg
    - assets/img/feature/wok on fire.webp
    - assets/img/Icons.jpeg
    - assets/img/icon.png
    - assets/img/img.png
    - assets/img/food/dhokla.png
    - assets/img/food/poha.png
    - assets/img/food/samosa.png
    - assets/img/food/thepla.png
    - assets/img/food/vada.png
    - assets/img/food/coffie.jpg
    - assets/img/discount.png
    - assets/img/filter.png


    - assets/img/food_images/dosa.png
    - assets/img/food_images/kachori.jpeg
    - assets/img/food_images/lassi.png
    - assets/img/food_images/momos.jpeg
    - assets/img/food_images/noodles.jpeg
    - assets/img/food_images/pasta.jpeg
    - assets/img/food_images/pavbhaji.jpeg
    - assets/img/food_images/pizza.jpeg
    - assets/img/food_images/poori.png
    - assets/img/food_images/roll.png
    - assets/img/food_images/salad.jpeg
    - assets/img/food_images/samosa.jpeg
    - assets/img/food_images/sandwich.png
    - assets/img/food_images/vada.png
    - assets/img/food_images/dosa.png
    - assets/img/food_images/burger.jpeg
    - assets/img/food_images/chinese.png
    - assets/img/food_images/biryani.png
    - assets/img/food_images/sandwich.png
    - assets/img/food_images/roll.png

    - assets/img/banner/banner1.png
    - assets/img/banner/banner2.png
    - assets/img/banner/banner3.png
    - assets/img/banner/banner4.png
    - assets/img/banner/banner5.png
    - assets/img/banner/banner6.png
    - assets/img/banner/banner7.png

    - assets/img/diamond/1.png
    - assets/img/diamond/2.png
    - assets/img/diamond/3.png
    - assets/img/diamond/4.png
    - assets/img/diamond/5.png
    - assets/img/diamond/6.png
    - assets/img/diamond/7.png

    - assets/img/hotel/h.jpg
    - assets/img/hotel/h1.jpg
    - assets/img/hotel/h2.jpg
    - assets/img/hotel/h3.jpg
    - assets/img/hotel/h4.jpg
    - assets/img/hotel/h5.jpg
    - assets/img/hotel/h6.jpg
    - assets/img/hotel/h7.jpg
    - assets/img/hotel/h8.jpg
    - assets/img/hotel/h9.jpg
    - assets/img/hotel/h10.jpg
    - assets/img/hotel/h11.jpg
    - assets/img/hotel/h12.jpg
    - assets/img/hotel/h14.jpg
    - assets/img/hotel/h15.jpg
    - assets/img/hotel/h16.jpg
    - assets/img/hotel/h17.jpg
    - assets/img/hotel/h18.jpg
    - assets/img/hotel/h19.jpg
    - assets/img/hotel/h20.jpg
    - assets/img/hotel/h21.jpg
    - assets/img/hotel/h22.jpg
    - assets/img/hotel/h23.jpg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
